Update docs for better security in CDN links
kognise/water.css pull request #230
Opened 2020-10-11 20:35 UTC by kylejrp

Added a [subresource integrity check attribute](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) and [crossorigin anonymou attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin).

This will ensure that anyone using the jsdelivr CDN won't be vulnerable to a security incident where a malicious stylesheet is served. ([Source 1](https://shkspr.mobi/blog/2020/10/please-stop-using-cdns-for-external-javascript-libraries/), [Source 2](https://www.smashingmagazine.com/2019/04/understanding-subresource-integrity/))

We will need to make a point of updating the integrity attributes when we release new versions. There's a [page on jsdelivr](https://www.jsdelivr.com/package/npm/water.css?path=out) where you can copy the HTML + SRI:
[![image](https://user-images.githubusercontent.com/6742479/95689546-54426680-0bc6-11eb-9c4e-89ce2dbca699.png)](https://www.jsdelivr.com/package/npm/water.css?path=out)

This also prevents people from easily changing the installation link from `water.css` to `water.min.css` since the integrity checks are different. We might want to add a `[ ] Minified` checkbox.

2020-10-11 20:39 UTC, kylejrp commented
This would make the installation box scroll, if that matters:
![image](https://user-images.githubusercontent.com/6742479/95689637-f1050400-0bc6-11eb-9e6b-fcbc9d94a1a4.png)

I think the copy to clipboard button makes this not a big deal though.

2020-10-12 01:46 UTC, jonaskuske commented
> We will need to make a point of updating the integrity attributes when we release new versions.

And we need to lock the version in the CDN link instead of specifying just `@2`, otherwise updates break every single site 😅

2020-10-12 01:47 UTC, jonaskuske requested changes

2020-10-12 01:47 UTC, jonaskuske commented on docs/index.html
> +        <pre id="link-snippet-auto"><code>&lt;link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css" integrity="sha256-HfKK0UZwALXyrCbFrMcV/bMDenCCcD3oBy4NUWLM7LA=" cross
Need to lock the version, instead of @2

2020-10-12 05:27 UTC, kylejrp commented
Great catch, @jonaskuske! Hah, that would have been awkward. 😅

2020-10-17 14:54 UTC, kognise commented
If we're properly following semver we should only be releasing breaking changes under major versions anyways. As for SRI, I'm not sure how much it would actually increase security. JSDelivr is very secure, and either way we're a CSS framework which doesn't have much surface for vulnerabilities except for people running really old versions of IE. Also, this will completely break Water.css for people getting the links from NPM, because NPM only shows the published README but we can't get the new SRI until after publishing.

2025-11-10 09:19 UTC, closed without merging